export HF_ENDPOINT=https://hf-mirror.com
# python train.py --gpu "1,2,3" --arch "mobilenet_v2" --batch_size 512 --lr 0.005 --epoch 100 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "resnet101.a1h_in1k" --batch_size 512 --lr 0.01 --epoch 150 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "resnet18.a1_in1k" --batch_size 512 --lr 0.01 --epoch 110 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
python at_train.py --gpu "1,2,3" --arch "resnet18-at" --batch_size 512 --lr 0.1 --epoch 200 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "inception_v3" --batch_size 512 --lr 0.01 --epoch 100 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "wide_resnet50_2.racm_in1k" --batch_size 512 --lr 0.01 --epoch 50 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "efficientnet_b0.ra4_e3600_r224_in1k" --batch_size 512 --lr 0.01 --epoch 50 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "efficientnet_lite0.ra_in1k" --batch_size 512 --lr 0.01 --epoch 50 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "resnet18.a1_in1k" --batch_size 512 --lr 0.005 --epoch 90 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set" --resume
# python train.py --gpu "1,2,3" --arch "resnet18.fb_swsl_ig1b_ft_in1k" --batch_size 512 --lr 0.01 --epoch 10 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set"
# python train.py --gpu "1,2,3" --arch "vit_tiny_patch16_224.augreg_in21k_ft_in1k" --batch_size 512 --lr 0.01 --epoch 10 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set"
# python train.py --gpu "1,2,3" --arch "efficientnet_lite0.ra_in1k" --batch_size 512 --lr 0.01 --epoch 10 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set"
# python train.py --gpu "1,2,3" --arch "wide_resnet50_2.racm_in1k" --batch_size 512 --lr 0.01 --epoch 10 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set"
# python train.py --gpu "1,2,3" --arch "vgg16.tv_in1k" --batch_size 512 --lr 0.01 --epoch 10 --train_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/train_set" --test_set "/data/hdd3/duhao/data/datasets/attack_dataset/phase1/test_set"
# python train.py --gpu "1,2,3" --arch "swint" --batch_size 512 --lr 0.001 --epoch 10
# python train.py --gpu "1,2,3" --arch "efficientnet_b0.ra4_e3600_r224_in1k" --batch_size 1024 --lr 0.001 --epoch 20 --train_set "/home/heshiyuan/code/adversarial_competition/data/phase1/train_set" --test_set "/home/heshiyuan/code/adversarial_competition/data/phase1/test_set"
# python train.py --gpu "0,1,2" --arch "densenet201.tv_in1k" --batch_size 512 --lr 0.001 --epoch 20 --train_set "/home/heshiyuan/code/adversarial_competition/data/phase1/train_set" --test_set "/home/heshiyuan/code/adversarial_competition/data/phase1/test_set"